name: CD - PRD
run-name: Deploy to ${{ inputs.project }}

on:
  workflow_dispatch:
    inputs:
      project:
        type: choice
        description: Choice a project
        required: true
        options:
          - sso
          - manager

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    with:
      BUILD_ENV: production
    secrets: inherit
  
  project-env:
    runs-on: ubuntu-latest
    outputs:
      PROJECT_ENV: ${{ steps.convert.outputs.PROJECT_ENV }}
    steps:
      - name: Convert inputs to uppercase and set environment variables
        id: convert
        run: |
          echo "::set-output name=PROJECT_ENV::$(echo ${{ inputs.project }} | tr '[:lower:]' '[:upper:]')"

  build-dependencies:
    needs: [setup]
    uses: ./.github/workflows/dependencies.yml
    with:
      BUILD_ENV: production
    secrets: inherit

  build-project:
    needs: [setup, project-env, build-dependencies]
    uses: ./.github/workflows/projects.yml
    with:
      ENVIRONMENT: ${{ needs.project-env.outputs.PROJECT_ENV }}
      BUILD_ENV: production
      PATH: dist
      PROJECT: ${{ inputs.project }}
      COMMAND: build
    secrets: inherit

  deploy-project:
    needs: [build-project, project-env]
    uses: ./.github/workflows/deploy.yml
    with:
      ENVIRONMENT: ${{ needs.project-env.outputs.PROJECT_ENV }}
      BUILD_ENV: production
      PATH: dist
      PROJECT: ${{ inputs.project }}
    secrets: inherit